image: node:9.11.1

stages:
  - test
  - deploy

before_script:
  - yarn install

cache:
  paths:
    - node_modules/

test:lint:
  script:
    - yarn lint

#test:unit-test:
#  script:
#    - yarn test

deploy_staging:
  stage: deploy
  script:
    - apt-get install software-properties-common
    - apt-add-repository ppa:brightbox/ruby-ng
    - apt-get update
    - apt-get install ruby2.5
    - gem install dpl
    - dpl --provider=heroku --app=proyect-excalibur --api-key=$HEROKU_API-KEY
  environment:
    name: heroku
    url: https://proyect-excalibur.herokuapp.com
  only:
    - develop
