image: node:9.11.1

stages:
  - test
  - deploy

before_script:
  - yarn install

cache:
  paths:
    - node_modules/

test:lint:
  script:
    - yarn lint

#test:unit-test:
#  script:
#    - yarn test

deploy_staging:
  stage: deploy
  script:
    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
    - apt-get update
    - apt-get install -y heroku-toolbelt
    - export HEROKU_API_KEY=$HEROKU_API_KEY
    - heroku container:push web --app proyect-excalibur
  environment:
    name: heroku
    url: https://proyect-excalibur.herokuapp.com
  only:
    - develop
