image: node:9.11.1

stages:
  - test
  - deploy


cache:
  paths:
    - node_modules/

test:lint:
  script:
    - yarn install
    - yarn lint

#test:unit-test:
#  script:
#    - yarn test

deploy_staging:
  stage: deploy
  image: ruby:2.1
  script:
    - gem install dpl
    - dpl --provider=heroku --app=viejo-relleno-bot --api-key=$HEROKU_API_KEY
  environment:
    name: heroku
    url: https://proyect-excalibur.herokuapp.com
  only:
    - develop
