image: node:10.1.0

stages:
  - deploy

cache:
  paths:
    - node_modules/

deploy_staging:
  stage: deploy
  image: ruby:2.2
  script:
    - gem install dpl
    - dpl --provider=heroku --app=proyect-excalibur --api-key=$HEROKU_API_KEY
  environment:
    name: heroku
    url: https://proyect-excalibur.herokuapp.com
  only:
    - master
